FROM node:20-slim AS build
WORKDIR /app
COPY / .
RUN npm install
RUN npm run build:prod

FROM nginx as final
COPY ./.nginx/nginx.conf /etc/nginx/nginx.conf
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 8080
CMD nginx -g 'daemon off;'